"""initial migration

Revision ID: 162f8e3fed45
Revises: 
Create Date: 2018-09-19 08:16:44.678929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162f8e3fed45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('thread', sa.String(length=255), nullable=True))
    op.drop_column('threads', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('threads', 'thread')
    # ### end Alembic commands ###
