"""added events

Revision ID: 568ddf9aea68
Revises: 162f8e3fed45
Create Date: 2018-09-19 16:45:17.080551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568ddf9aea68'
down_revision = '162f8e3fed45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=True),
    sa.Column('event_description', sa.String(length=250), nullable=True),
    sa.Column('event_location', sa.String(length=50), nullable=True),
    sa.Column('event_charges', sa.String(length=50), nullable=True),
    sa.Column('event_poster', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
