"""added guides

Revision ID: 8c34e3ef35e1
Revises: 568ddf9aea68
Create Date: 2018-09-20 10:49:47.177953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c34e3ef35e1'
down_revision = '568ddf9aea68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guides')
    # ### end Alembic commands ###
